service: api-backend

frameworkVersion: "3"

custom:
    secrets: ${file(secrets.json)}
    optimize:
        external: ["swagger-ui-dist", "bcrypt"]
    apigwBinary:
        types:
            - "*/*"

plugins:
    - serverless-plugin-typescript
    - serverless-plugin-optimize
    - serverless-offline
    - serverless-apigw-binary

package:
    individually: true

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1
    # vpc:
    #     securityGroupIds:
    #         - ${ssm:/secrets/SECURITY_GROUP_ID}
    #     subnetIds:
    #         - ${ssm:/secrets/SUBNET_ID}
    environment:
        TOKEN_KEY: ${ssm:/ApiBackendKK/secrets/TOKEN_KEY}
        # TEST_ENV: ${ssm:/TestVariable}
    tags:
        Name: api-backend
        Description: "Proyecto final KK"
        Responsible: "Desarrollador Backend Fabio Anaya"
        ProjectName: "Api Backend"
        Environment: pdn
        creationDate: 2022-02-15
        resourceType: private
        dataType: private
    apiGateway:
        restApiId: ${ssm:/ApiBackendKK/secrets/REST_API_ID}
        restApiRootResourceId: ${ssm:/ApiBackendKK/secrets/REST_API_RESOURCE_ID}
        apiKeys:
            - name: apiKey
              value: ${ssm:/ApiBackendKK/secrets/CUSTOM_AUTHORIZER}
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - dynamodb:DescribeTable
                      - dynamodb:Query
                      - dynamodb:Scan
                      - dynamodb:GetItem
                      - dynamodb:PutItem
                      - dynamodb:UpdateItem
                  Resource:
                      - "Fn::GetAtt": [ApiBackendUsersTable, Arn]
                      - "Fn::GetAtt": [ApiBackendKKPostsTable, Arn]
                - Effect: "Allow"
                  Action:
                      - lambda:InvokeFunction
                      - lambda:InvokeAsync
                  Resource: "*"

functions:
    main:
        handler: src/lambda.handler
        timeout: 29
        events:
            - http:
                  method: get
                  path: /user/ping
                  private: true
                  cors: true
            - http:
                  cors: true
                  method: post
                  path: /auth/login
                  private: true
            - http:
                  cors: true
                  method: post
                  path: /auth/register
                  private: true
            - http:
                  cors: true
                  method: get
                  path: /user/refresh-token
                  private: true
            - http:
                  cors: true
                  method: post
                  path: /post
                  private: true
            - http:
                  cors: true
                  method: get
                  path: /post
                  private: true
            - http:
                  cors: true
                  method: put
                  path: /post
                  private: true
            - http:
                  cors: true
                  method: delete
                  path: /post
                  private: true
resources:
    - ${file(aws-resources/dynamodb.yml)}
    - Resources:
          GatewayResponseDefault4XX:
              Type: "AWS::ApiGateway::GatewayResponse"
              Properties:
                  ResponseParameters:
                      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,<your-custom-header-goes-here>'"
                  ResponseType: DEFAULT_4XX
                  RestApiId:
                      Ref: ${ssm:/ApiBackendKK/secrets/REST_API_ID}
          GatewayResponseDefault5XX:
              Type: "AWS::ApiGateway::GatewayResponse"
              Properties:
                  ResponseParameters:
                      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
                      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent,<your-custom-header-goes-here>'"
                  ResponseType: DEFAULT_5XX
                  RestApiId:
                      Ref: ${ssm:/ApiBackendKK/secrets/REST_API_ID}
