Resources:
    ApiBackendUsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: api-backend-kk-users
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            SSESpecification:
                SSEEnabled: true
    ApiBackendKKPostsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: api-backend-kk-posts
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST
            SSESpecification:
                SSEEnabled: true
